# Generated by Django 4.2.2 on 2026-04-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='start_timr',
            new_name='start_time',
        ),
    ]
